FROM python:3.12-slim

WORKDIR /app/server

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    httpx \
    beanie \
    pymongo

COPY server/main.py ./main.py
COPY server/core ./core
COPY server/models ./models
COPY server/repositories ./repositories
COPY server/routers ./routers
COPY server/schemas ./schemas
COPY server/services ./services

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

