function wait(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

function cfgSum(cfg) {
  return Object.values(cfg).reduce((sum, v) => {
    if (typeof v === 'number') {
      return sum + v;
    }
    return sum + String(v).length;
  }, 0);
}

export async function runGenerate(node) {
  await wait(240);
  return {
    artifact: `${node.data.type.toLowerCase()}_${node.id}.v`
  };
}

export async function runVerify(node, nodes, edges) {
  await wait(220);
  if (edges.length === 0 && nodes.length > 1) {
    throw new Error('graph has isolated balls');
  }
  return {
    pass: true
  };
}

export async function runEvaluate(node) {
  await wait(280);
  const base = cfgSum(node.data.cfg);
  return {
    latency: base * 4 + node.data.type.length * 13,
    area: base * 7 + node.data.type.length * 19
  };
}

export function exportVerilog(nodes, edges) {
  if (nodes.length === 0) {
    throw new Error('graph is empty');
  }
  const modules = nodes.map((n) => {
    return `module ${n.data.type.toLowerCase()}_${n.id}(input clk, input rst_n); endmodule`;
  });
  const wires = edges.map((e, i) => {
    return `wire link_${i}; // ${e.source} -> ${e.target}`;
  });
  return [
    '// Auto generated by EDEIN',
    ...wires,
    ...modules
  ].join('\n');
}
