const API_BASE = import.meta.env.VITE_API_BASE || 'http://localhost:8000';

function mapNode(node) {
  if (!node) {
    return null;
  }
  return {
    id: node.id,
    type: node.data?.type,
    cfg: node.data?.cfg || {}
  };
}

function mapGraph(nodes, edges) {
  return {
    nodes: nodes.map((n) => ({
      id: n.id,
      type: n.data?.type,
      cfg: n.data?.cfg || {}
    })),
    edges: edges.map((e) => ({
      source: e.source,
      target: e.target
    }))
  };
}

async function runTask(kind, node, nodes, edges) {
  const response = await fetch(`${API_BASE}/api/tasks`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json'
    },
    body: JSON.stringify({
      kind,
      node: mapNode(node),
      graph: mapGraph(nodes, edges)
    })
  });

  const body = await response.json();
  if (!response.ok) {
    throw new Error(body.detail || 'request failed');
  }
  if (body.status !== 'success') {
    throw new Error(body.error || `${kind} failed`);
  }
  return body;
}

export async function runGenerate(node, nodes, edges) {
  const task = await runTask('generate', node, nodes, edges);
  return task.result;
}

export async function runVerify(node, nodes, edges) {
  const task = await runTask('verify', node, nodes, edges);
  return task.result;
}

export async function runEvaluate(node, nodes, edges) {
  const task = await runTask('evaluate', node, nodes, edges);
  return task.result;
}

export async function sendChat(message, payload) {
  const response = await fetch(`${API_BASE}/api/chat`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json'
    },
    body: JSON.stringify({ message, payload })
  });

  const body = await response.json();
  if (!response.ok) {
    throw new Error(body.detail || 'chat failed');
  }
  return body;
}

export function exportVerilog(nodes, edges) {
  if (nodes.length === 0) {
    throw new Error('graph is empty');
  }
  const modules = nodes.map((n) => {
    return `module ${n.data.type.toLowerCase()}_${n.id}(input clk, input rst_n); endmodule`;
  });
  const wires = edges.map((e, i) => {
    return `wire link_${i}; // ${e.source} -> ${e.target}`;
  });
  return [
    '// Auto generated by EDEIN',
    ...wires,
    ...modules
  ].join('\n');
}
